### ISSUE TITLE
Cards in carousel issues 

### ISSUE THREAD

**Issue by Francescap10** [wsfuller/html5-css3-class#10]
Cards in carousel about page 

[scrolling-bootstrap-card-carousel-4-production.zip](https://github.com/wsfuller/html5-css3-class/files/2279313/scrolling-bootstrap-card-carousel-4-production.zip)
[scrolling-bootstrap-card-carousel-tv-shows.zip](https://github.com/wsfuller/html5-css3-class/files/2279314/scrolling-bootstrap-card-carousel-tv-shows.zip)

**Comment by wsfuller** [comment]
Issues reported in this repo should only pertain to content here within
